version: "3"
services:
  app:
    image: toancong/cv:darknet
    volumes:
      - .:/darknet/app
      - ./train/Images:/darknet/Images
      - ./train/Labels:/darknet/Labels
      - ./train/Examples:/darknet/Examples
      # - ./train/bblt/main.py:/BBox-Label-Tool/main.py
    environment:
      - DISPLAY=docker.for.mac.host.internal:0
    working_dir: /darknet
    command:
    - /bin/bash
    - -c
    - |
      python app/app.py
  se:
    image: toancong/feup:node6
    volumes:
      - .:/data/www/current
